### PR TITLE
Feature/http requests

### PR DESCRIPTION
**Pull request by foekinator656**
please merge this so i can work in a feature branch!

### CODE REVIEW

**Comment by foekinator656** [comment]
@DragonTamer117

**Comment by DragonTamer117** [comment]
Can you stop annoying me, let's be serious. :)

**Comment by foekinator656** [comment]
ik kan niet meer pushen :(

**Comment by DragonTamer117** [comment]
> ik kan niet meer pushen :(

Only English, please :)

**Review by DragonTamer117 — APPROVED** [review]
LGTM!

**Review by DragonTamer117 — DISMISSED** [review]
LGTM!

**Review by DragonTamer117 — APPROVED** [review]
LGTM!

**Pull request merged**
